name: ğŸ”® CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  tests-and-quality:
    runs-on: ubuntu-latest
    permissions: {}
    concurrency:
      group: ${{ github.workflow }}-test-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: â¬ Install uv
        uses: astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3 #  v7.1.3
      - name: âœ¨ Reformat source files
        run: uv run ruff format --check
      - name: âœ¨ Check source files
        run: uv run ruff check
      - name: ğŸ¤¹ Run tests suite
        run: uv run pytest
